# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f29dc9a7c49bfc603996527c71696810a9d136c73ed8acf8f6e38396cc8bfdcf1876aa2b33fd36d61f42272857a0b30963ce152c49be4044a97bf8209b5b4d54

test:
  secret_key_base: 1020b9916e00c0f1bbf0e34607cedbbe6d0926bb2f09e14f49d729af103735191665727f2fd2ffb5a2e1124aecc764f4e5ef5816173a55a24a747a707707aa57

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
